#! /bin/sh

### Autostart ###
polybar custom -r &
xsetroot -cursor_name left_ptr &
sxhkd &
feh --bg-fill ~/dotfiles/wallpapers/Pictures/Wallpapers/wallpaper4.jpg
picom -b --experimental-backends
fcitx -d
flameshot &
setxkbmap -option caps:swapescape
dunst &
sh -c ~/dotfiles/.scripts/cmus_daemon.sh &

### Gaps ###
bspc config top_padding        2
bspc config bottom_padding     2
bspc config left_padding       2
bspc config right_padding      2
bspc config border_width       2
bspc config window_gap         8

### Focusing behavior ###
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config focus_by_distance true

bspc monitor -d 1 2 3 4 5 6 7 8

### Multihead behavior ###
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colors
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#6272a4"
